### ISSUE TITLE
Arduino Json 7 API

### ISSUE THREAD

**Issue by trullock** [mathieucarbou/ESPAsyncWebServer#10]
Hi,

Thanks for this fork and all the updates made.

What is meant by

> Arduino Json 7 compatibility and by default, still compatible with 6 (AsyncJson.h)

Are you saying AsyncJson.h should only be used for V6? (I can see that it's API is V6 focused with legacy V5 support).

How am I supposed to parse a JSON body using V7? A quick example or pointer would be appreciated

Thanks

**Comment by mathieucarbou** [comment]
Hello, I have updated the readme to clarify.
Nothing changes from user perspective. The are internals.

**Comment by trullock** [comment]
Thanks 😊
