### ISSUE TITLE
[BUG] ESPAsyncWebServer issue with RP2040 and W5500

### ISSUE THREAD

**Issue by MicSG-dev** [mathieucarbou/ESPAsyncWebServer#102]
**Description**

Arduino IDE 2.0 does not compile the basic ESPAsyncWebServer library example (CaptivePortal example).
I have already installed the AsyncTCP_RP2040W library.

**Board**

Raspberry Pi Pico (RP2040)

**Ethernet adapter used?**

W5500 mini

**Compilation error**
c:\Users\Michel\Documents\Arduino\libraries\AsyncTCP_RP2040W\src/AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
73 | #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
| ^~~~~
exit status 1

Compilation error: exit status 1

**Additional Notes**

My Raspberry Pi Pico board does not have WiFi.

**Comment by mathieucarbou** [comment]
Hello,

I don't look at issues coming from Arduino IDE, sorry. 
This is not a real IDE but a toy that is not handling transitive dependencies correctly and does not allow easy maintenance of a per project settings (board, platform, etc).

Please try again with PlatformIO, which has a stringer dependency mechanism with

```ini
lib_compat_mode = strict
lib_ldf_mode = chain
```

And if not solved, please post the board, platform, etc you are using in your pio file so that I can test.

You can also have a look at this project's config here: https://github.com/mathieucarbou/ESPAsyncWebServer/blob/main/platformio.ini#L56-L63

**Comment by MicSG-dev** [comment]
Thank you. I did what you asked.

platformio.ini
```
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = Generic
framework = arduino
board_build.core = earlephilhower
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
  bblanchon/ArduinoJson @ 7.1.0
  khoih-prog/AsyncTCP_RP2040W @ 1.2.0
  https://github.com/mathieucarbou/ESPAsyncWebServer.git
```

Code main.cpp:
```
#include <DNSServer.h>
#include <WebServer.h>
#include <WiFi.h>
#include "ESPAsyncWebServer.h"

void setup() {
 
}

void loop() {
}
```

Error displayed:
```
C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src\http_parser.c:1:10: fatal error: ../lib/http-parser/http_parser.c: No such file or directory
    1 | #include "../lib/http-parser/http_parser.c"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio\build\pico\lib352\ESPAsyncWebServer\AsyncEventSource.cpp.o
*** [.pio\build\pico\lib16b\http-parser\http_parser.c.o] Error 1
C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\lwIP_ESPHost\src\ESPHost.cpp:22:10: fatal error: CEspControl.h: No such file or directory

*********************************************************************
* Looking for CEspControl.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:CEspControl.h"
* Web  > https://registry.platformio.org/search?q=header:CEspControl.h
*
*********************************************************************

   22 | #include <CEspControl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\pico\libf54\lwIP_ESPHost\ESPHost.cpp.o] Error 1
In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\lwIP_ESPHost\src\lwIP_ESPHost.cpp:21:
C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\lwIP_ESPHost\src\lwIP_ESPHost.h:24:10: fatal error: CCtrlWrapper.h: No such file or directory

**********************************************************************
* Looking for CCtrlWrapper.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:CCtrlWrapper.h"
* Web  > https://registry.platformio.org/search?q=header:CCtrlWrapper.h
*
**********************************************************************

   24 | #include "CCtrlWrapper.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\pico\libf54\lwIP_ESPHost\lwIP_ESPHost.cpp.o] Error 1
In file included from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncPrinter.h:51,
                 from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncPrinter.cpp:51:
.pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
   73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
      |    ^~~~~
In file included from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.cpp:104:
.pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
   73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
      |    ^~~~~
In file included from .pio\libdeps\pico\AsyncTCP_RP2040W\src\SyncClient.cpp:53:
.pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
   73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
      |    ^~~~~
In file included from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W_buffer.h:60,
                 from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W_buffer.cpp:58:
.pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
   73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
      |    ^~~~~
In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/HTTP_Method.h:3,
                 from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/HTTPServer.h:28,
                 from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/WebServerTemplate.h:23,
                 from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/WebServer.h:23,
                 from src\main.cpp:2:
C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src/http_parser.h:1:10: fatal error: ../lib/http-parser/http_parser.h: No such file or directory
    1 | #include "../lib/http-parser/http_parser.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\pico\src\main.cpp.o] Error 1
In file included from .pio\libdeps\pico\ESPAsyncWebServer\src\AsyncEventSource.h:37,
                 from .pio\libdeps\pico\ESPAsyncWebServer\src\AsyncEventSource.cpp:24:
.pio\libdeps\pico\AsyncTCP_RP2040W\src/AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
   73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
      |    ^~~~~
In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTP_Method.h:3,
                 from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTPServer.h:28,
                 from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\Parsing.cpp:25:
C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src/http_parser.h:1:10: fatal error: ../lib/http-parser/http_parser.h: No such file or directory
    1 | #include "../lib/http-parser/http_parser.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTP_Method.h:3,
                 from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTPServer.h:28,
                 from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTPServer.cpp:27:
C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src/http_parser.h:1:10: fatal error: ../lib/http-parser/http_parser.h: No such file or directory
    1 | #include "../lib/http-parser/http_parser.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\pico\lib9fa\WebServer\HTTPServer.cpp.o] Error 1
*** [.pio\build\pico\lib9fa\WebServer\Parsing.cpp.o] Error 1
In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/HTTP_Method.h:3,
                 from .pio\libdeps\pico\ESPAsyncWebServer\src/ESPAsyncWebServer.h:39,
                 from .pio\libdeps\pico\ESPAsyncWebServer\src\AsyncEventSource.h:43:
C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src/http_parser.h:1:10: fatal error: ../lib/http-parser/http_parser.h: No such file or directory
    1 | #include "../lib/http-parser/http_parser.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\pico\lib352\ESPAsyncWebServer\AsyncEventSource.cpp.o] Error 1
*** [.pio\build\pico\lib0c0\AsyncTCP_RP2040W\SyncClient.cpp.o] Error 1
*** [.pio\build\pico\lib0c0\AsyncTCP_RP2040W\AsyncPrinter.cpp.o] Error 1
*** [.pio\build\pico\lib0c0\AsyncTCP_RP2040W\AsyncTCP_RP2040W.cpp.o] Error 1
*** [.pio\build\pico\lib0c0\AsyncTCP_RP2040W\AsyncTCP_RP2040W_buffer.cpp.o] Error 1
================================================================================================= [FAILED] Took 3.02 seconds =================================================================================================
```

From what I understand, libraries are not compatible with the non-WiFi version of the RP2040 .is there nothing that can be done?

**Comment by mathieucarbou** [comment]
> Thank you. I did what you asked.
> 
> platformio.ini
> 
> ```
> [env:pico]
> platform = https://github.com/maxgerhardt/platform-raspberrypi.git
> board = Generic
> framework = arduino
> board_build.core = earlephilhower
> lib_compat_mode = strict
> lib_ldf_mode = chain
> lib_deps = 
>   bblanchon/ArduinoJson @ 7.1.0
>   khoih-prog/AsyncTCP_RP2040W @ 1.2.0
>   https://github.com/mathieucarbou/ESPAsyncWebServer.git
> ```
> 
> Code main.cpp:
> 
> ```
> #include <DNSServer.h>
> #include <WebServer.h>
> #include <WiFi.h>
> #include "ESPAsyncWebServer.h"
> 
> void setup() {
>  
> }
> 
> void loop() {
> }
> ```
> 
> Error displayed:
> 
> ```
> C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src\http_parser.c:1:10: fatal error: ../lib/http-parser/http_parser.c: No such file or directory
>     1 | #include "../lib/http-parser/http_parser.c"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> Compiling .pio\build\pico\lib352\ESPAsyncWebServer\AsyncEventSource.cpp.o
> *** [.pio\build\pico\lib16b\http-parser\http_parser.c.o] Error 1
> C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\lwIP_ESPHost\src\ESPHost.cpp:22:10: fatal error: CEspControl.h: No such file or directory
> 
> *********************************************************************
> * Looking for CEspControl.h dependency? Check our library registry!
> *
> * CLI  > platformio lib search "header:CEspControl.h"
> * Web  > https://registry.platformio.org/search?q=header:CEspControl.h
> *
> *********************************************************************
> 
>    22 | #include <CEspControl.h>
>       |          ^~~~~~~~~~~~~~~
> compilation terminated.
> *** [.pio\build\pico\libf54\lwIP_ESPHost\ESPHost.cpp.o] Error 1
> In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\lwIP_ESPHost\src\lwIP_ESPHost.cpp:21:
> C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\lwIP_ESPHost\src\lwIP_ESPHost.h:24:10: fatal error: CCtrlWrapper.h: No such file or directory
> 
> **********************************************************************
> * Looking for CCtrlWrapper.h dependency? Check our library registry!
> *
> * CLI  > platformio lib search "header:CCtrlWrapper.h"
> * Web  > https://registry.platformio.org/search?q=header:CCtrlWrapper.h
> *
> **********************************************************************
> 
>    24 | #include "CCtrlWrapper.h"
>       |          ^~~~~~~~~~~~~~~~
> compilation terminated.
> *** [.pio\build\pico\libf54\lwIP_ESPHost\lwIP_ESPHost.cpp.o] Error 1
> In file included from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncPrinter.h:51,
>                  from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncPrinter.cpp:51:
> .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>    73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>       |    ^~~~~
> In file included from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.cpp:104:
> .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>    73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>       |    ^~~~~
> In file included from .pio\libdeps\pico\AsyncTCP_RP2040W\src\SyncClient.cpp:53:
> .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>    73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>       |    ^~~~~
> In file included from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W_buffer.h:60,
>                  from .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W_buffer.cpp:58:
> .pio\libdeps\pico\AsyncTCP_RP2040W\src\AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>    73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>       |    ^~~~~
> In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/HTTP_Method.h:3,
>                  from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/HTTPServer.h:28,
>                  from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/WebServerTemplate.h:23,
>                  from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/WebServer.h:23,
>                  from src\main.cpp:2:
> C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src/http_parser.h:1:10: fatal error: ../lib/http-parser/http_parser.h: No such file or directory
>     1 | #include "../lib/http-parser/http_parser.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> *** [.pio\build\pico\src\main.cpp.o] Error 1
> In file included from .pio\libdeps\pico\ESPAsyncWebServer\src\AsyncEventSource.h:37,
>                  from .pio\libdeps\pico\ESPAsyncWebServer\src\AsyncEventSource.cpp:24:
> .pio\libdeps\pico\AsyncTCP_RP2040W\src/AsyncTCP_RP2040W.h:73:4: error: #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>    73 |   #error For RASPBERRY_PI_PICO_W board using CYW43439 WiFi only
>       |    ^~~~~
> In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTP_Method.h:3,
>                  from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTPServer.h:28,
>                  from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\Parsing.cpp:25:
> C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src/http_parser.h:1:10: fatal error: ../lib/http-parser/http_parser.h: No such file or directory
>     1 | #include "../lib/http-parser/http_parser.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTP_Method.h:3,
>                  from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTPServer.h:28,
>                  from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src\HTTPServer.cpp:27:
> C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src/http_parser.h:1:10: fatal error: ../lib/http-parser/http_parser.h: No such file or directory
>     1 | #include "../lib/http-parser/http_parser.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> *** [.pio\build\pico\lib9fa\WebServer\HTTPServer.cpp.o] Error 1
> *** [.pio\build\pico\lib9fa\WebServer\Parsing.cpp.o] Error 1
> In file included from C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\WebServer\src/HTTP_Method.h:3,
>                  from .pio\libdeps\pico\ESPAsyncWebServer\src/ESPAsyncWebServer.h:39,
>                  from .pio\libdeps\pico\ESPAsyncWebServer\src\AsyncEventSource.h:43:
> C:\Users\MichelGalvao\.platformio\packages\framework-arduinopico\libraries\http-parser\src/http_parser.h:1:10: fatal error: ../lib/http-parser/http_parser.h: No such file or directory
>     1 | #include "../lib/http-parser/http_parser.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> *** [.pio\build\pico\lib352\ESPAsyncWebServer\AsyncEventSource.cpp.o] Error 1
> *** [.pio\build\pico\lib0c0\AsyncTCP_RP2040W\SyncClient.cpp.o] Error 1
> *** [.pio\build\pico\lib0c0\AsyncTCP_RP2040W\AsyncPrinter.cpp.o] Error 1
> *** [.pio\build\pico\lib0c0\AsyncTCP_RP2040W\AsyncTCP_RP2040W.cpp.o] Error 1
> *** [.pio\build\pico\lib0c0\AsyncTCP_RP2040W\AsyncTCP_RP2040W_buffer.cpp.o] Error 1
> ================================================================================================= [FAILED] Took 3.02 seconds =================================================================================================
> ```
> 
> From what I understand, libraries are not compatible with the non-WiFi version of the RP2040 .is there nothing that can be done?

Hi,
Thanks for your data.
It is correct, except that the supported board at the moment is only the WiFi one: I get the same error when switching to non wifi and also when using the release repo instead of the main branch (`#include <CEspControl.h>`)

If you look at the stack trace, you will see that the issue comes from `AsyncTCP_RP2040W` library, which is used by ESPAsyncWS. So you need to redirect your issue to the author of this library.

Thanks!

**Comment by MicSG-dev** [comment]
Got it, thank you very much.
