### ISSUE TITLE
[BUG] setAuthentication on serveStatic not working from 3.3.x

### ISSUE THREAD

**Issue by rostwolke** [mathieucarbou/ESPAsyncWebServer#151]
**Description**

First, thanks for the good work! After switching from the me-no-dev version of the repo I noticed that my web ui does not ask me for authentication anymore. The code to reproduce this is simply:
```
server->serveStatic("/", SPIFFS, "/www/").setDefaultFile("index.html").setAuthentication("test", "test");
```

I checked when the problem occurred for the first time. I switched versions back in arduino and the 3.0.6 is the first one that seems to work again.

**Link:** See example above.

**Board**: ESP32-C3 Super Mini

**Ethernet adapter used ?** No

**Stack trace**

Should not be necessary since the ESP does not crash.

**Additional notes**

I noticed that this version of the async webserver supports middleware. I am sure I can fix my problem using middleware. I still wanted to inform you since setAuthentication is still listed in the docs.

**Comment by mathieucarbou** [comment]
Thanks for the bug report! Indeed, I saw a bug which was introduced when adding backward compatibility for middleware support. I will fix now.

**Comment by mathieucarbou** [comment]
A workaround is to use middleware

**Comment by rostwolke** [comment]
@mathieucarbou Works like a charm. Thanks again and keep up the good work :-)
