### ISSUE TITLE
ArduinoJson dependency

### ISSUE THREAD

**Issue by vortigont** [mathieucarbou/ESPAsyncWebServer#2]
I see that in your for you defined ArduinoJson lib as dependency. Is there any specific code in this fork added that won't build without ArduinoJson?
The reason I'm asking is that other projects using AsyncServer might have their own dependency on ArduinoJson v6, so introducing strict dependency might create some issues.

Tnx!

**Comment by mathieucarbou** [comment]
So I added that following the switch from 6 to 7, but I've kept 6 compat'.

But looking again you're right that only `AsyncJson.h` requires ArduinoJon (like all the previous forks).

Which means this dependency should be optional.

I will fix that

**Comment by vortigont** [comment]
Nice, thanks!
