### ISSUE TITLE
problème avec safari sur les fichiers compressé

### ISSUE THREAD

**Issue by xlyric** [mathieucarbou/ESPAsyncWebServer#22]
Salut, 

Safari ne faisant rien comme les autres, lors qu'il charge une page, il peux charger une autre page dans certains cas 
exemple : 

```
 server.on("/log.html", HTTP_ANY, [](AsyncWebServerRequest *request){
        AsyncWebServerResponse *response = request->beginResponse(LittleFS, "/log.html.gz", "text/html");
        response->addHeader("Content-Encoding", "gzip");
        request->send(response);
  });
```
 

sur des navigateurs classiques, il prends log.html, sur safari il tentera de récuperer /log.html.gz

pour résoudre il faut virer la ligne 
`544   addHeader(F("Content-Disposition"), buf);  dans WebResonses.cpp`

**Comment by mathieucarbou** [comment]
@xlyric : could you please test the fix by pointing to `https://github.com/mathieucarbou/ESPAsyncWebServer#issue-22` ?

Thanks :-)

**Comment by xlyric** [comment]
je te tente de te fais ça dans la soirée 
cdt

**Comment by xlyric** [comment]
c'est bon de mon coté, ça fonctionne. 
cdt
Cyril

**Comment by mathieucarbou** [comment]
v2.9.5 released. Thanks!
