### ISSUE TITLE
[BUG] Implement macro version check as part of your CI

### ISSUE THREAD

**Issue by ayushsharma82** [mathieucarbou/ESPAsyncWebServer#50]
I noticed your v3.0.4 release didn't have the right version set in macros, it should be part of your CI for safe releases.

**Comment by ayushsharma82** [comment]
It can be implemented by comparing version strings in `library.json`, `library.properties` and then regex to get the version macros in `ESPAsyncWebServer.h` file.

**Comment by mathieucarbou** [comment]
thanks! this one slipped yes. hopefully this is just the minor version, nobody should use it in theory.

**Comment by mathieucarbou** [comment]
Fixed in abcd2df5e087ef712cb7e5145a60812c473423f4
