### ISSUE TITLE
[BUG] ESPAsyncWebServer.h question

### ISSUE THREAD

**Issue by lidodvr224** [mathieucarbou/ESPAsyncWebServer#73]
Running newest versions, Windows/ArduinoIDE 232+ 30Jul24 nightly. (v313)
line157 change error:

Documents\Arduino\libraries\ESPAsyncWebServer\src/ESPAsyncWebServer.h: In member function 'String AsyncWebHeader::toString() const':
c:\Users\jelli\Documents\Arduino\libraries\ESPAsyncWebServer\src/ESPAsyncWebServer.h:157:44: error: ambiguous overload for 'operator+' (operand types are 'const String' and 'char')
  157 |     String toString() const { return _name + (char)0x3a + (char)0x20 /*": "*/ + _value + asyncsrv::T_rn; }
      |                                      ~~~~~ ^ ~~~~~~~~~~
      |                                      |       |
      |                                      |       char
      |                                      const String

Thank you for any feedback.

**Comment by mathieucarbou** [comment]
That's a bug.
@vortigont : FYI

**Comment by mathieucarbou** [comment]
@lidodvr224 : can you please try with branch to verify this is fixed ?

 #bugfix (https://github.com/mathieucarbou/ESPAsyncWebServer/tree/bugfix) ?
 
 Thanks!

**Comment by lidodvr224** [comment]
yes, standby...

**Comment by lidodvr224** [comment]
v 3.13 with new ESPAsyncWebServer.h (28261 bytes) from 12Aug24 built, and
my application is working as expected with MycilaWebSerial (630).
will update this on github.
thank you!
