### ISSUE TITLE
Fix send() overload - char* vs String&

### ISSUE THREAD

**Issue by mathieucarbou** [mathieucarbou/ESPAsyncWebServer#79]
### Discussed in https://github.com/mathieucarbou/ESPAsyncWebServer/discussions/78

<div type='discussions-op-text'>

<sup>Originally posted by **ddprog** August 30, 2024</sup>
I can't understand why this construction doesn't compile:
```
webServer.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {request->send(LittleFS, "index.html");});
```</div>

**Comment by ddprog** [comment]
Thank you!
